<?php
$config = [
    'development' => [
        'server' => [
            'document_root' => 'BASE_PATH',
            'webserver_http' => 'https://wordpress.local',
            'php_cli_binary' => '/Applications/MAMP/bin/php/php8.0.8',
            'timezone' => 'Europe/Berlin',
        ],
        'database' => [
            'username' => 'root1',
            'password' => 'root',
            'host' => '127.0.0.1',
            'port' => '3306',
            'dbname' => 'pressmind',
            'engine' => 'MySQL',
        ],
        'rest' => [
            'client' => [
                'api_key' => 'e91bad26e8594a523b88cc46e6184718',
                'api_user' => 'weltenbummler.com@pressmind-travelshop',
                'api_password' => 'e8eb4b46a6e53a1f9963b0328c8d7d64',
            ],
            'server' => [
                'api_endpoint' => '/wp-content/themes/travelshop/rest',
                'api_key' => '',
                'api_user' => '',
                'api_password' => '',
            ],
        ],
        'tmp_dir' => 'APPLICATION_PATH/tmp',
        'docs_dir' => 'APPLICATION_PATH/docs',
        'logging' => [
            'mode' => [
                0 => 'ERROR',
            ],
            'categories' => [
                0 => 'ALL',
            ],
            'storage' => 'database',
            'log_file_path' => 'APPLICATION_PATH/logs',
            'error_email_address' => 'john.doe@local',
            'lifetime' => 86400,
            'keep_log_types' => [
                0 => 'ERROR',
            ],
            'enable_advanced_object_log' => false,
            'enable_database_query_logging' => false,
            'database_query_log_file' => 'APPLICATION_PATH/logs/db_query_log.txt',
        ],
        'debug' => [
            'mode' => 'on',
            'ip_addresses' => [
                0 => '127.0.0.1',
            ],
        ],
        'data' => [
            'touristic' => [
                'origins' => [
                    0 => '0',
                ],
                'my_content_class_map' => [
                ],
                'disable_touristic_data_import' => [
                    0 => 912,
                    1 => 913,
                    2 => 914,
                ],
                'generate_single_room_index' => false,
                'max_offers_per_product' => 5000,
            ],
            'media_type_custom_import_hooks' => [
                912 => [
                    0 => 'Custom\\IBETeamImport',
                ],
                913 => [
                    0 => 'Custom\\IBETeamImport',
                ],
                914 => [
                    0 => 'Custom\\IBETeamImport',
                ],
            ],
            'primary_media_type_ids' => [
                0 => 912,
                1 => 913,
                2 => 914,
            ],
            'media_types' => [
                912 => 'Reise',
                913 => 'Unterkunft',
                914 => 'Tagesfahrt',
                915 => 'Laenderinformationen',
                1044 => 'Zielgebiet',
                1312 => 'Globale_textbausteine',
                1419 => 'Urls',
            ],
            'media_types_pretty_url' => [
                912 => [
                    'prefix' => '/reise/',
                    'fields' => [
                        'name' => 'name',
                    ],
                    'strategy' => 'count-up',
                    'suffix' => '/',
                ],
                913 => [
                    'prefix' => '/unterkunft/',
                    'fields' => [
                        'name' => 'name',
                    ],
                    'strategy' => 'count-up',
                    'suffix' => '/',
                ],
                914 => [
                    'prefix' => '/tagesfahrt/',
                    'fields' => [
                        'name' => 'name',
                    ],
                    'strategy' => 'count-up',
                    'suffix' => '/',
                ],
                915 => [
                    'prefix' => '/laenderinformationen/',
                    'fields' => [
                        'name' => 'name',
                    ],
                    'strategy' => 'count-up',
                    'suffix' => '/',
                ],
                1044 => [
                    'prefix' => '/zielgebiet/',
                    'fields' => [
                        'name' => 'name',
                    ],
                    'strategy' => 'count-up',
                    'suffix' => '/',
                ],
                1312 => [
                    'prefix' => '/globale_textbausteine/',
                    'fields' => [
                        'name' => 'name',
                    ],
                    'strategy' => 'count-up',
                    'suffix' => '/',
                ],
                1419 => [
                    'prefix' => '/urls/',
                    'fields' => [
                        'name' => 'name',
                    ],
                    'strategy' => 'count-up',
                    'suffix' => '/',
                ],
            ],
            'media_types_fulltext_index_fields' => [
                912 => [
                    'name' => 'name',
                    'code' => 'code',
                    'tags' => 'tags',
                    'kuschick_code_default' => 'kuschick_code_default',
                    'tabelle_default' => 'tabelle_default',
                    'reisedauer_default' => 'reisedauer_default',
                    'video_default' => 'video_default',
                    'unterkunftverknuepfung_default' => 'unterkunftverknuepfung_default',
                    'bilder_default' => 'bilder_default',
                    'karte_default' => 'karte_default',
                    'title_default' => 'title_default',
                    'hinweis_headline_default' => 'hinweis_headline_default',
                    'tipp_headline_default' => 'tipp_headline_default',
                    'tipp_headline_print' => 'tipp_headline_print',
                    'reiseleiter_empfehlung_headline_default' => 'reiseleiter_empfehlung_headline_default',
                    'headline_default' => 'headline_default',
                    'leistungen_headline_default' => 'leistungen_headline_default',
                    'leistungen_extra_text_default' => 'leistungen_extra_text_default',
                    'fruehbucherrabatt_default' => 'fruehbucherrabatt_default',
                    'leistungen_extra_headline_print_default' => 'leistungen_extra_headline_print_default',
                    'reisetyp_default' => 'reisetyp_default',
                    'steuerung_unterkunft_print_default' => 'steuerung_unterkunft_print_default',
                    'googlemaps_default' => 'googlemaps_default',
                    'meta_description_default' => 'meta_description_default',
                    'tipp_subline_default' => 'tipp_subline_default',
                    'tipp_subline_print' => 'tipp_subline_print',
                    'subline_default' => 'subline_default',
                    'leistungen_default' => 'leistungen_default',
                    'reiseleiter_empfehlung_default' => 'reiseleiter_empfehlung_default',
                    'hinweis_text_default' => 'hinweis_text_default',
                    'leistungen_extra_text_print_default' => 'leistungen_extra_text_print_default',
                    'fluss_default' => 'fluss_default',
                    'steuerung_hinweis_print_default' => 'steuerung_hinweis_print_default',
                    'steuerung_unterkunft_bild_print_default' => 'steuerung_unterkunft_bild_print_default',
                    'meta_keywords_default' => 'meta_keywords_default',
                    'reiseleiter_name_default' => 'reiseleiter_name_default',
                    'routentabelle_default' => 'routentabelle_default',
                    'einleitung_default' => 'einleitung_default',
                    'leistungen_extra_pdf_1_text_default' => 'leistungen_extra_pdf_1_text_default',
                    'tipp_text_default' => 'tipp_text_default',
                    'tipp_text_print' => 'tipp_text_print',
                    'rederei_default' => 'rederei_default',
                    'steuerung_unterkunft_bildhoehe_print_default' => 'steuerung_unterkunft_bildhoehe_print_default',
                    'leistungen_extra_pdf_1_default' => 'leistungen_extra_pdf_1_default',
                    'textbaustein_default' => 'textbaustein_default',
                    'reiseleiter_bild_default' => 'reiseleiter_bild_default',
                    'logo_default' => 'logo_default',
                    'meta_robots_default' => 'meta_robots_default',
                    'tipp_zusatz_default' => 'tipp_zusatz_default',
                    'tipp_zusatz_print' => 'tipp_zusatz_print',
                    'schiffsbezeichnungen_default' => 'schiffsbezeichnungen_default',
                    'steuerung_reiseleiter_print_default' => 'steuerung_reiseleiter_print_default',
                    'meta_revisit_default' => 'meta_revisit_default',
                    'tipp_2_headline_default' => 'tipp_2_headline_default',
                    'tipp_2_headline_print' => 'tipp_2_headline_print',
                    'hinweis_headline_www_default' => 'hinweis_headline_www_default',
                    'reisehighlights_default' => 'reisehighlights_default',
                    'leistungen_extra_pdf_2_text_default' => 'leistungen_extra_pdf_2_text_default',
                    'leistungen_extra_pdf_2_default' => 'leistungen_extra_pdf_2_default',
                    'header_source_code_default' => 'header_source_code_default',
                    'treueherzen_default' => 'treueherzen_default',
                    'tipp_2_subline_default' => 'tipp_2_subline_default',
                    'tipp_2_subline_print' => 'tipp_2_subline_print',
                    'hinweis_headline_text_default' => 'hinweis_headline_text_default',
                    'reiseart_default' => 'reiseart_default',
                    'steuerung_beschreibung_headline_und_bild_print_default' => 'steuerung_beschreibung_headline_und_bild_print_default',
                    'footer_source_code_default' => 'footer_source_code_default',
                    'tipp_2_text_default' => 'tipp_2_text_default',
                    'tipp_2_text_print' => 'tipp_2_text_print',
                    'hinweis_hochseekreuzfahrt_tabelle_default' => 'hinweis_hochseekreuzfahrt_tabelle_default',
                    'saison_default' => 'saison_default',
                    'url_default' => 'url_default',
                    'beschreibung_headline_default' => 'beschreibung_headline_default',
                    'tipp_2_zusatz_default' => 'tipp_2_zusatz_default',
                    'tipp_2_zusatz_print' => 'tipp_2_zusatz_print',
                    'zielgebiet_default' => 'zielgebiet_default',
                    'url_verknuepfung_default' => 'url_verknuepfung_default',
                    'beschreibung_text_default' => 'beschreibung_text_default',
                    'hotelkategorie_default' => 'hotelkategorie_default',
                    'verpflegungsart_default' => 'verpflegungsart_default',
                    'verkaufsprioritaet_default' => 'verkaufsprioritaet_default',
                    'hinweise_pdf_1_text_default' => 'hinweise_pdf_1_text_default',
                    'optionen_default' => 'optionen_default',
                    'hinweise_pdf_1_default' => 'hinweise_pdf_1_default',
                    'farbsteuerung_default' => 'farbsteuerung_default',
                    'steuerung_termine_preise_print_default' => 'steuerung_termine_preise_print_default',
                    'freitextstoerer_oben_default' => 'freitextstoerer_oben_default',
                    'freitextstoerer_unten_default' => 'freitextstoerer_unten_default',
                ],
                913 => [
                    'name' => 'name',
                    'code' => 'code',
                    'tags' => 'tags',
                    'geodaten_default' => 'geodaten_default',
                    'logo_default' => 'logo_default',
                    'kuschick_code_default' => 'kuschick_code_default',
                    'hinweis_text_default' => 'hinweis_text_default',
                    'zielgebiet_default' => 'zielgebiet_default',
                    'textbausteine_default' => 'textbausteine_default',
                    'zielgebietsverknuepfung_default' => 'zielgebietsverknuepfung_default',
                    'bilder_default' => 'bilder_default',
                    'title_default' => 'title_default',
                    'headline_default' => 'headline_default',
                    'hotelkategorie_default' => 'hotelkategorie_default',
                    'ferienzielpendel_default' => 'ferienzielpendel_default',
                    'subline_default' => 'subline_default',
                    'unterkunftart_default' => 'unterkunftart_default',
                    'zimmer_default' => 'zimmer_default',
                    'meta_description_default' => 'meta_description_default',
                    'einleitung_default' => 'einleitung_default',
                    'url_verknuepfung_default' => 'url_verknuepfung_default',
                    'beschreibung_text_default' => 'beschreibung_text_default',
                    'highlights_default' => 'highlights_default',
                    'kategorie_default' => 'kategorie_default',
                    'indikationen_default' => 'indikationen_default',
                    'reisetyp_default' => 'reisetyp_default',
                    'hotellink_default' => 'hotellink_default',
                    'decksplan_default' => 'decksplan_default',
                    'kabine_default' => 'kabine_default',
                    'kabine_headline_default' => 'kabine_headline_default',
                    'kabine_text_default' => 'kabine_text_default',
                    'kabinenzuteilung_default' => 'kabinenzuteilung_default',
                    'zimmer_headline_default' => 'zimmer_headline_default',
                    'zimmer_text_default' => 'zimmer_text_default',
                    'leistungen_default' => 'leistungen_default',
                    'treueherzen_pendel_default' => 'treueherzen_pendel_default',
                ],
                914 => [
                    'name' => 'name',
                    'code' => 'code',
                    'tags' => 'tags',
                    'saison_default' => 'saison_default',
                    'video_default' => 'video_default',
                    'bilder_default' => 'bilder_default',
                    'meta_description_default' => 'meta_description_default',
                    'headline_default' => 'headline_default',
                    'zielgebiet_default' => 'zielgebiet_default',
                    'title_default' => 'title_default',
                    'subline_default' => 'subline_default',
                    'reiseart_default' => 'reiseart_default',
                    'beschreibung_headline_default' => 'beschreibung_headline_default',
                    'beschreibung_text_default' => 'beschreibung_text_default',
                ],
                915 => [
                    'name' => 'name',
                    'code' => 'code',
                    'tags' => 'tags',
                    'headline_textbaustein_default' => 'headline_textbaustein_default',
                    'text_default' => 'text_default',
                    'einreiseinformationen_default' => 'einreiseinformationen_default',
                    'ortstaxe_default' => 'ortstaxe_default',
                ],
                1044 => [
                    'name' => 'name',
                    'code' => 'code',
                    'tags' => 'tags',
                    'zielgebiet_default' => 'zielgebiet_default',
                    'bilder_default' => 'bilder_default',
                    'headline_default' => 'headline_default',
                    'beschreibung_text_default' => 'beschreibung_text_default',
                    'an_und_abreise_default' => 'an_und_abreise_default',
                ],
                1312 => [
                    'name' => 'name',
                    'code' => 'code',
                    'tags' => 'tags',
                    'reisetyp_default' => 'reisetyp_default',
                    'text_default' => 'text_default',
                ],
                1419 => [
                    'name' => 'name',
                    'code' => 'code',
                    'tags' => 'tags',
                    'url_default' => 'url_default',
                    'title_default' => 'title_default',
                    'description_default' => 'description_default',
                    'seo_text_default' => 'seo_text_default',
                ],
            ],
            'sections' => [
                'allowed' => [
                    0 => 'Default',
                ],
                'default' => 'Default',
                'fallback' => 'Default',
                'fallback_on_empty_values' => true,
                'replace' => [
                    'regular_expression' => NULL,
                    'replacement' => NULL,
                ],
            ],
            'languages' => [
                'allowed' => [
                    0 => 'de',
                ],
                'default' => 'de',
            ],
            'preview_url' => '/examples/detail.php?id={{id_media_object}}&preview={{preview}}',
            'search_mongodb' => [
                'enabled' => true,
                'database' => [
                    'uri' => 'mongodb+srv://pressmind_sdk:374Hgdtfp00873Hjngt@cluster1.idfm3.mongodb.net/admin?authSource=admin&replicaSet=atlas-4jrsyk-shard-0&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true',
                    'db' => 'michaelamting-dev',
                ],
                'search' => [
                    'build_for' => [
                        912 => [
                            0 => [
                                'language' => NULL,
                                'origin' => 0,
                            ],
                        ],
                        913 => [
                            0 => [
                                'language' => NULL,
                                'origin' => 0,
                            ],
                        ],
                        914 => [
                            0 => [
                                'language' => NULL,
                                'origin' => 0,
                            ],
                        ],
                    ],
                    'code_delimiter' => ',',
                    'groups' => [
                        0 => [
                            123 => [
                                'field' => 'agencies',
                                'filter' => NULL,
                            ],
                        ],
                        1 => [
                            124 => [
                                'field' => 'id_pool',
                                'filter' => NULL,
                            ],
                        ],
                        2 => [
                            125 => [
                                'field' => 'brand',
                                'filter' => NULL,
                            ],
                        ],
                        3 => [
                            126 => [
                                'field' => 'website_ausgabe_default',
                                'filter' => '\\Custom\\Filter::treeToGroup',
                            ],
                        ],
                    ],
                    'categories' => [
                        912 => [
                            'reisedauer_default' => NULL,
                            'reisetyp_default' => NULL,
                            'steuerung_unterkunft_print_default' => NULL,
                            'fluss_default' => NULL,
                            'steuerung_hinweis_print_default' => NULL,
                            'steuerung_unterkunft_bild_print_default' => NULL,
                            'rederei_default' => NULL,
                            'steuerung_unterkunft_bildhoehe_print_default' => NULL,
                            'schiffsbezeichnungen_default' => NULL,
                            'steuerung_reiseleiter_print_default' => NULL,
                            'reiseart_default' => NULL,
                            'steuerung_beschreibung_headline_und_bild_print_default' => NULL,
                            'saison_default' => NULL,
                            'zielgebiet_default' => NULL,
                            'hotelkategorie_default' => NULL,
                            'verpflegungsart_default' => NULL,
                            'verkaufsprioritaet_default' => NULL,
                            'optionen_default' => NULL,
                            'farbsteuerung_default' => NULL,
                            'steuerung_termine_preise_print_default' => NULL,
                        ],
                        913 => [
                            'zielgebiet_default' => NULL,
                            'hotelkategorie_default' => NULL,
                            'ferienzielpendel_default' => NULL,
                            'unterkunftart_default' => NULL,
                            'indikationen_default' => NULL,
                            'reisetyp_default' => NULL,
                        ],
                        914 => [
                            'saison_default' => NULL,
                            'zielgebiet_default' => NULL,
                            'reiseart_default' => NULL,
                        ],
                    ],
                    'descriptions' => [
                        912 => [
                            'name' => [
                                'field' => 'name',
                                'from' => NULL,
                                'filter' => NULL,
                            ],
                            'headline' => [
                                'field' => 'headline_default',
                                'from' => NULL,
                                'filter' => NULL,
                            ],
                            'stoerer_oben' => [
                                'field' => 'freitextstoerer_oben_default',
                                'from' => NULL,
                                'filter' => NULL,
                            ],
                            'stoerer_unten' => [
                                'field' => 'freitextstoerer_unten_default',
                                'from' => NULL,
                                'filter' => NULL,
                            ],
                            'image' => [
                                'field' => 'bilder_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::firstPicture',
                                'params' => [
                                    'derivative' => 'teaser_medium',
                                    'section' => 'base',
                                ],
                            ],
                            'bigslide' => [
                                'field' => 'bilder_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::firstPicture',
                                'params' => [
                                    'derivative' => 'bigslide',
                                    'section' => 'panorama',
                                ],
                            ],
                            'image_square' => [
                                'field' => 'bilder_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::firstPicture',
                                'params' => [
                                    'derivative' => 'square',
                                    'section' => 'quadrate',
                                ],
                            ],
                            'highlights' => [
                                'field' => 'reisehighlights_default',
                                'from' => NULL,
                                'filter' => NULL,
                            ],
                            'subline' => [
                                'field' => 'subline_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::strip',
                            ],
                            'intro' => [
                                'field' => 'einleitung_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::strip',
                            ],
                            'travel_type' => [
                                'field' => 'reiseart_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::lastTreeItemAsString',
                            ],
                            'reisetyp' => [
                                'field' => 'reisetyp_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::lastTreeItemAsString',
                            ],
                            'reisetyp_id' => [
                                'field' => 'reisetyp_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::lastTreeItemIdAsString',
                            ],
                            'destination' => [
                                'field' => 'zielgebiet_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::lastTreeItemAsString',
                            ],
                        ],
                        914 => [
                            'name' => [
                                'field' => 'name',
                                'from' => NULL,
                                'filter' => NULL,
                            ],
                            'headline' => [
                                'field' => 'headline_default',
                                'from' => NULL,
                                'filter' => NULL,
                            ],
                            'image' => [
                                'field' => 'bilder_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::firstPicture',
                                'params' => [
                                    'derivative' => 'teaser_medium',
                                    'section' => 'base',
                                ],
                            ],
                            'bigslide' => [
                                'field' => 'bilder_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::firstPicture',
                                'params' => [
                                    'derivative' => 'bigslide',
                                    'section' => 'panorama',
                                ],
                            ],
                            'image_square' => [
                                'field' => 'bilder_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::firstPicture',
                                'params' => [
                                    'derivative' => 'square',
                                    'section' => 'quadrate',
                                ],
                            ],
                            'subline' => [
                                'field' => 'subline_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::strip',
                            ],
                            'intro' => [
                                'field' => 'einleitung_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::strip',
                            ],
                            'travel_type' => [
                                'field' => 'reiseart_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::lastTreeItemAsString',
                            ],
                            'destination' => [
                                'field' => 'zielgebiet_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::lastTreeItemAsString',
                            ],
                        ],
                        913 => [
                            'name' => [
                                'field' => 'name',
                                'from' => NULL,
                                'filter' => NULL,
                            ],
                            'headline' => [
                                'field' => 'headline_default',
                                'from' => NULL,
                                'filter' => NULL,
                            ],
                            'image' => [
                                'field' => 'bilder_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::firstPicture',
                                'params' => [
                                    'derivative' => 'teaser_medium',
                                    'section' => 'base',
                                ],
                            ],
                            'bigslide' => [
                                'field' => 'bilder_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::firstPicture',
                                'params' => [
                                    'derivative' => 'bigslide',
                                    'section' => 'panorama',
                                ],
                            ],
                            'image_square' => [
                                'field' => 'bilder_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::firstPicture',
                                'params' => [
                                    'derivative' => 'square',
                                    'section' => 'quadrate',
                                ],
                            ],
                            'highlights' => [
                                'field' => 'highlights_default',
                                'from' => NULL,
                                'filter' => NULL,
                            ],
                            'subline' => [
                                'field' => 'subline_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::strip',
                            ],
                            'intro' => [
                                'field' => 'einleitung_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::strip',
                            ],
                            'reisetyp' => [
                                'field' => 'reisetyp_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::lastTreeItemAsString',
                            ],
                            'rating' => [
                                'field' => 'hotelkategorie_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::lastTreeItemAsString',
                            ],
                            'reisetyp_id' => [
                                'field' => 'reisetyp_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::lastTreeItemIdAsString',
                            ],
                            'destination' => [
                                'field' => 'zielgebiet_default',
                                'from' => NULL,
                                'filter' => '\\Custom\\Filter::lastTreeItemAsString',
                            ],
                        ],
                    ],
                    'five_dates_per_month_list' => false,
                    'possible_duration_list' => false,
                    'allow_invalid_offers' => false,
                    'touristic' => [
                        'departure_offset_from' => 14,
                        'departure_offset_to' => 730,
                        'occupancies' => [
                            0 => 1,
                            1 => 2,
                            2 => 3,
                            3 => 4,
                            4 => 5,
                            5 => 6,
                        ],
                        'occupancy_additional' => [
                            0 => 1,
                            1 => 2,
                        ],
                        'duration_ranges' => [
                            0 => [
                                0 => 1,
                                1 => 3,
                            ],
                            1 => [
                                0 => 4,
                                1 => 7,
                            ],
                            2 => [
                                0 => 8,
                                1 => 99,
                            ],
                        ],
                    ],
                ],
            ],
            'media_types_allowed_visibilities' => [
                912 => [
                    0 => 30,
                ],
                913 => [
                    0 => 30,
                ],
                914 => [
                    0 => 30,
                ],
                915 => [
                    0 => 30,
                ],
                1044 => [
                    0 => 30,
                ],
                1312 => [
                    0 => 30,
                ],
                1419 => [
                    0 => 30,
                ],
            ],
        ],
        'cache' => [
            'enabled' => false,
            'adapter' => [
                'name' => 'Redis',
                'config' => [
                    'host' => '127.0.0.1',
                    'port' => 6379,
                    'connection_string' => NULL,
                ],
            ],
            'key_prefix' => 'DATABASE_NAME',
            'disable_parameter' => [
                'key' => 'no_cache',
                'value' => 1,
            ],
            'update_parameter' => [
                'key' => 'update_cache',
                'value' => 1,
            ],
            'types' => [
                0 => 'REST',
                1 => 'SEARCH',
                2 => 'SEARCH_FILTER',
                3 => 'OBJECT',
                4 => 'MONGODB',
            ],
            'update_frequency' => 3600,
            'max_idle_time' => 86400,
        ],
        'view_scripts' => [
            'base_path' => 'APPLICATION_PATH/template-parts/pm-views',
        ],
        'scaffolder_templates' => [
            'overwrite_existing_templates' => false,
            'base_path' => 'APPLICATION_PATH/template-parts/pm-views/scaffolder',
        ],
        'file_handling' => [
            'processor' => [
            ],
            'storage' => [
                'provider' => 'filesystem',
                'bucket' => 'WEBSERVER_DOCUMENT_ROOT/wp-content/uploads/pressmind/downloads',
                'credentials' => [
                ],
            ],
            'http_src' => 'WEBSERVER_HTTP/wp-content/uploads/pressmind/downloads',
        ],
        'image_handling' => [
            'processor' => [
                'adapter' => 'ImageMagick',
                'webp_support' => true,
                'derivatives' => [
                    'thumbnail' => [
                        'max_width' => 125,
                        'max_height' => 78,
                        'preserve_aspect_ratio' => true,
                        'crop' => true,
                        'horizontal_crop' => 'center',
                        'vertical_crop' => 'center',
                        'webp_create' => true,
                        'webp_quality' => 80,
                    ],
                    'teaser' => [
                        'max_width' => 250,
                        'max_height' => 156,
                        'preserve_aspect_ratio' => true,
                        'crop' => true,
                        'horizontal_crop' => 'center',
                        'vertical_crop' => 'center',
                        'webp_create' => true,
                        'webp_quality' => 80,
                    ],
                    'teaser_medium' => [
                        'max_width' => 500,
                        'max_height' => 312,
                        'preserve_aspect_ratio' => true,
                        'crop' => true,
                        'horizontal_crop' => 'center',
                        'vertical_crop' => 'center',
                        'webp_create' => true,
                        'webp_quality' => 80,
                    ],
                    'teaser_original' => [
                        'max_width' => 640,
                        'max_height' => NULL,
                        'preserve_aspect_ratio' => true,
                        'crop' => false,
                        'horizontal_crop' => 'center',
                        'vertical_crop' => 'center',
                        'webp_create' => true,
                        'webp_quality' => 80,
                    ],
                    'square' => [
                        'max_width' => 480,
                        'max_height' => 480,
                        'preserve_aspect_ratio' => true,
                        'crop' => true,
                        'horizontal_crop' => 'center',
                        'vertical_crop' => 'center',
                        'webp_create' => true,
                        'webp_quality' => 80,
                    ],
                    'detail_thumb' => [
                        'max_width' => 90,
                        'max_height' => 90,
                        'preserve_aspect_ratio' => true,
                        'crop' => true,
                        'horizontal_crop' => 'center',
                        'vertical_crop' => 'center',
                        'webp_create' => true,
                        'webp_quality' => 80,
                    ],
                    'detail' => [
                        'max_width' => 730,
                        'max_height' => 460,
                        'preserve_aspect_ratio' => true,
                        'crop' => true,
                        'horizontal_crop' => 'center',
                        'vertical_crop' => 'center',
                        'webp_create' => true,
                        'webp_quality' => 80,
                    ],
                    'detail_gallery' => [
                        'max_width' => 1200,
                        'max_height' => 750,
                        'preserve_aspect_ratio' => true,
                        'crop' => true,
                        'horizontal_crop' => 'center',
                        'vertical_crop' => 'center',
                        'webp_create' => true,
                        'webp_quality' => 80,
                    ],
                    'detail_gallery_original' => [
                        'max_width' => 1200,
                        'max_height' => NULL,
                        'preserve_aspect_ratio' => true,
                        'crop' => true,
                        'horizontal_crop' => 'center',
                        'vertical_crop' => 'center',
                        'webp_create' => true,
                        'webp_quality' => 80,
                    ],
                    'bigslide' => [
                        'max_width' => 1980,
                        'max_height' => 600,
                        'preserve_aspect_ratio' => true,
                        'crop' => true,
                        'horizontal_crop' => 'center',
                        'vertical_crop' => 'center',
                        'webp_create' => true,
                        'webp_quality' => 80,
                    ],
                ],
            ],
            'storage' => [
                'provider' => 'filesystem',
                'bucket' => 'WEBSERVER_DOCUMENT_ROOT/wp-content/uploads/pressmind/images',
                'credentials' => [
                ],
            ],
            'http_src' => 'WEBSERVER_HTTP/wp-content/uploads/pressmind/images',
        ],
        'scheduled_tasks' => [
            0 => [
                'name' => 'Log Clean Up',
                'class_name' => '\\Pressmind\\Log\\Service',
                'schedule' => [
                    'type' => 'Daily',
                    'time' => 'Fixed',
                    'value' => '23:30',
                    'max_running_time_in_minutes' => 1440,
                ],
                'methods' => [
                    0 => [
                        'method' => 'cleanUp',
                        'parameters' => NULL,
                        'position' => 1,
                    ],
                ],
            ],
            1 => [
                'name' => 'Cache Clean Up',
                'class_name' => '\\Pressmind\\Cache\\Service',
                'schedule' => [
                    'type' => 'Minutely',
                    'time' => 'Period',
                    'value' => '5',
                    'max_running_time_in_minutes' => 1440,
                ],
                'methods' => [
                    0 => [
                        'method' => 'cleanUp',
                        'parameters' => NULL,
                        'position' => 1,
                    ],
                ],
            ],
        ],
    ],
    'testing' => [
    ],
    'production' => [
    ],
];